# Generated by Django 4.2.5 on 2023-09-26 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0002_foods_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_general.orders'),
        ),
    ]
