# Generated by Django 4.2.5 on 2023-10-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0003_reservation_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='foods_name',
            field=models.CharField(max_length=100),
        ),
    ]
