# Generated by Django 4.2.5 on 2023-10-22 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0006_orderitem_orders_completed_orders_date_ordered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='foods',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_general.foods'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_general.orders'),
        ),
    ]
