# Generated by Django 4.2.5 on 2023-10-23 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0007_orderitem_foods_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='foods',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='queue',
        ),
        migrations.AddField(
            model_name='foods',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='orders',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_general.profile'),
        ),
    ]
