# Generated by Django 4.2.5 on 2023-10-23 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0009_customer_alter_orders_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='amount',
        ),
    ]
