# Generated by Django 4.2.5 on 2023-10-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0010_remove_orders_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='price',
        ),
    ]
